language: php
php:
  - '7.2'
dist: trusty
#notifications:
#  slack: prepperlearning:VgHyCXQ8lq11Qonx7OFYEGoA
branches:
  only:
    - master
#install:
#  - npm install
script:
  - echo 'hello'
#  - npm run set-env
#  - npm run test
#  - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] ; then
#  npm run clean;
#  npm run build
#  ; fi'
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: o5nDuaebSkZZS3fPdYmZQ44s7piWusKsbd8XdPWggzFOzxfbj91aSZzWzyVG/1jZ8IRoUD2IU/B9ef90tWrSePhEqhF36A7OqtOPUFwJraYRbFj5dQlqOh5y7bF+7SzrkusmgIOJ93a9i9FPRgt97CgMcWtiOC+98JQW4JIWDH/XY5BGxpvjjTidnXxaLKoL6OJPim59XZ8qoGR2QqioLqOnNjZsP56fZqJB/cG86ZoozX7LTJsuhEAeqgYgFu6wii9AG9MsvOSWdtFWHM0mEuyZD1TH9J6mjsKoQezFNXKsF0Tgv6nyt63jjqzDnvrQd1If/C6AzgSjCBggJ8wiDgKWJ9bSU+FVZ6JgPHVLzFF6D4rkwstCxNHsNa4mrMtiqRygDJzzQAQGT+KHJG7g4C1whMmYfflYxdPj3UE6wmISQrbIm03KqKFD5yGh2Nofz0wQzk6VKRtjFZVPYVQ9lXJqaE666U/xQjRGn+n19W0zRCulQ/+NeVm74v1PUBySZxsS7BtLhYfbJhDws+Sn3O4h9/YXeOGut/+c7Rf8xbJNKk3PrHrHXQ1wO5DE2KBV7hoNoAEGjDs7qkSuGLsKXfdsbTiQkinYxbxV7rgDexBh3zIxySLpVMw85uTewsK+9VbsLXsyF0DyX7//ko4SIpL0NIhme4CSR3N8z1th2Ds=
  on:
    branch: master
